apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  name: caikit-example-isvc
spec:
  predictor:
    model:
      modelFormat:
        name: caikit
      runtime: caikit-runtime
      storageUri: <Path to location with config.yml and artifacts directory>